version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/v2"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10

  - package-ecosystem: "docker"
    directory: "/v2"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/v2/proxy"
    target-branch: "v4"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
